application: madfrets
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /upload
  static_dir: upload
- url: /
  script: login.php
- url: /play
  script: play.php
- url: /share
  script: share.php
